"""empty message

Revision ID: 2687104df806
Revises: 823872fb8547
Create Date: 2024-12-19 05:37:26.703741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2687104df806'
down_revision = '823872fb8547'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('timing_hours', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('timing_minutes', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('timing_minutes')
        batch_op.drop_column('timing_hours')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
